autoDiscovery:
  clusterName: ${CLUSTER_NAME}
awsRegion: ${AWS_REGION}
image:
  tag: v1.34.0
nodeSelector:
  operational: "true"
  monitor: "true"
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
extraArgs:
  skip-nodes-with-system-pods: false
  scale-down-unneeded-time: 30s
  scale-down-unready-time: 1m
  # for large scale workload
  kube-client-qps: 300
  kube-client-burst: 400
rbac:
  serviceAccount:
    create: false
    name: cluster-autoscaler